x-app: &default-app
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true

services:
  postgres:
    <<: *default-app
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_POSTGRES_CPUS:-0}"
          memory: "${DOCKER_POSTGRES_MEMORY:-0}"
    image: "postgres:14.1-bullseye"
    healthcheck:
      test: pg_isready -U postgres
      interval: "10s"
      timeout: "3s"
      retries: 3
    volumes:
      - "postgres:/var/lib/postgresql/data"

  web:
    <<: *default-app
    image: "convertility-api:0.0.1-SNAPSHOT"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:8080}:8080"

volumes:
  postgres: {}
