spring:
  datasource:
    url: ${DATASOURCE:jdbc:postgresql://postgres:5432/convertility}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

linkedin:
  client-key: ${LINKEDIN_CLIENT}
  client-secret: ${LINKEDIN_SECRET}
  redirect-uri: ${LINKEDIN_REDIRECT_URI:http://localhost:8080/api/v1/auth2}

server:
  servlet:
    context-path: /api/v1
